name: Android UI Tests CI

on:
  workflow_dispatch:

jobs:
  ui-test:
    name: Run UI Tests
    runs-on: ubuntu-latest
    timeout-minutes: 120
    strategy:
      matrix:
        api-level: [ 30 ] # Add more API levels if needed: [29, 30, 33]

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Enable KVM
        run: |
          echo 'KERNEL=="kvm", GROUP="kvm", MODE="0666", OPTIONS+="static_node=kvm"' | sudo tee /etc/udev/rules.d/99-kvm4all.rules
          sudo udevadm control --reload-rules
          sudo udevadm trigger --name-match=kvm

      - name: Install required packages (merged apt calls)
        run: |
          sudo apt-get update
          sudo apt-get install -y libx11-6 libvulkan1 android-sdk-platform-tools-common

      - name: Gradle cache
        uses: gradle/actions/setup-gradle@v3

      - name: AVD cache
        uses: actions/cache@v4
        id: avd-cache
        with:
          path: |
            ~/.android/avd/*
            ~/.android/adb*
          key: avd-${{ matrix.api-level }}

      - name: Create AVD snapshot for caching
        if: steps.avd-cache.outputs.cache-hit != 'true'
        uses: reactivecircus/android-emulator-runner@v2
        with:
          api-level: ${{ matrix.api-level }}
          arch: x86_64
          force-avd-creation: false
          emulator-options: -cores 2 -gpu auto -no-window -noaudio -no-boot-anim
          disable-animations: true
          script: echo "Generated AVD snapshot for caching."

      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          distribution: 'adopt'
          java-version: '19'
          cache: 'gradle'

      - name: Add ADB to PATH
        run: echo "$ANDROID_HOME/platform-tools" >> $GITHUB_PATH

      - name: Restart ADB Daemon
        run: |
          adb kill-server
          adb start-server
          
      - name: Make gradlew executable
        run: chmod +x gradlew
        
      - name: Instrumentation Tests
        uses: reactivecircus/android-emulator-runner@v2
        with:
          api-level: ${{ matrix.api-level }}
          target: google_apis
          arch: x86_64
          force-avd-creation: false
          emulator-boot-timeout: 600
          emulator-options: -cores 2 -gpu auto -no-window -noaudio -no-boot-anim
          disable-animations: true
          script: |
            adb wait-for-device
            adb shell settings put global animator_duration_scale 0
            adb shell settings put global transition_animation_scale 0
            adb shell settings put global window_animation_scale 0
            ./gradlew connectedAndroidTest
